"""Stamp the firmware with the git revision at build time.

The version a person reads off the glass used to be a hand-edited string
(AppScenes.h said "0.6.0" while dist/ said the same and the actual commit
was anyone's guess). A bug report needs the exact build, not a marketing
number someone forgot to bump.

This writes include/generated/xphone_version.h before every build:

    XPHONE_GIT_REV     "fw-v0.5-15-g868bb1a-dirty"   git describe
    XPHONE_MARKETING   "0.6.0"                        the human-facing series

`git describe --tags` is deliberate — the repo's fw-v0.5 is a LIGHTWEIGHT
tag, which plain `git describe` (annotated-only) skips, falling back to a
bare hash. `--always` keeps a shallow/tagless checkout building; `--dirty`
marks an uncommitted working tree, so a bench build is never mistaken for
a clean tagged one.
"""
Import("env")  # noqa: F821  (PlatformIO injects this)
import subprocess
import os

MARKETING = "0.7.4"


def git_rev():
    try:
        out = subprocess.run(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=env.subst("$PROJECT_DIR"),  # noqa: F821
            capture_output=True, text=True, timeout=10)
        rev = out.stdout.strip()
        return rev or "unknown"
    except Exception:
        return "unknown"


def main():
    rev = git_rev()
    out_dir = os.path.join(env.subst("$PROJECT_DIR"), "include", "generated")  # noqa: F821
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "xphone_version.h")
    body = (
        "// Generated by tools/gen_version.py before every build. Do not edit.\n"
        "#pragma once\n"
        f'#define XPHONE_GIT_REV "{rev}"\n'
        f'#define XPHONE_MARKETING "{MARKETING}"\n'
    )
    # Only rewrite on change, so an unchanged rev does not force a rebuild.
    prev = None
    if os.path.exists(path):
        with open(path) as f:
            prev = f.read()
    if prev != body:
        with open(path, "w") as f:
            f.write(body)
    print(f"[gen_version] {rev}")


main()
